# Site settings
title: Random Wall
email: prakashpvss@gmail.com
description: "PV's Blog - Python, Machine Learning, C++"
baseurl: ""
url: "http://pvss.github.io"
twitter_username: pvss
github_username:  pvss

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

