# Site settings
# Site settings
title: Random Wall | PVs Blog
email: "prakashpvss@gmail.com"
description: "Random Posts."
baseurl: ""
url: "http://pvss.github.io"
github_username:  PVSS

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
